---
nav:
  - Home: index.md
  - HomeLab:
      - content/homelab/index.md
      - JamLab Family Guides: content/homelab/family.md
      - JamLab Nomad: content/homelab/jamlabnomad.md
      - Networking: content/homelab/networking.md
      - Power: content/homelab/power.md
      - Rack: content/homelab/rack.md
      - Raspberry Pi: 
          - Installation: content/homelab/rpi.md
          - PiVPN: content/homelab/pivpn.md
      - Synology DS220+:
          - Installation: content/homelab/ds220.md
      - HP DL380 G9:
          - Installation: content/homelab/dl380g9.md
          - Operating System: content/homelab/os.md
      - Operating systems: 
          - Proxmox VE: content/homelab/proxmox.md
      - Configuration Management:
          - Ansible: content/homelab/ansible.md
          - Ansible Vault: content/homelab/ansiblevault.md
          - Mozilla SOPS: content/homelab/sops.md
      - Provisioning:
          - Hashicorp Packer: content/homelab/packer.md
          - Hashicorp Terraform: content/homelab/terraform.md
      - DNS: 
          - General DNS: content/homelab/dns.md
          - Dnsmasq: content/homelab/dnsmasq.md
      - Container Orchestration:
          - Hashicorp Consul: content/homelab/consul.md
          - Hashicorp Nomad: content/homelab/nomad.md
          - Kubernetes: content/homelab/kubernetes.md
  - DevOps:
      - content/devops/index.md
      - Version Control:
          - Semantic Versioning: content/devops/semver.md
          - Git For Beginners: content/devops/gitbasics.md
          - Git DOs & DON'Ts: content/devops/gitdos.md
          - Precommit: content/devops/precommit.md
      - Configuration Management: 
          - Ansible User's Guide to Saltstack: content/devops/saltstack-for-ansible.md
      - GitLab:
          - OpenStack Packer GitLab CI/CD: content/devops/packerci.md
          - Sharing Runners To Multiple Projects: content/devops/gitlabrunnershare.md
      - Orchestration:
          - Orchestration Fundamentals Explained Simply: content/devops/orchestrationexplained.md
      - Secrets Management:
          - Vault with AD: content/devops/vaultad.md
          - Vault with Kerberos: content/devops/vaultkrb.md
      - AI:
          - Prompt Engineering: content/devops/prompteng.md
  - Food & Drinks:
      - content/food/index.md
      - JamFox's:
          - Drinks: content/food/drinks.md
          - Basics: content/food/basics.md
          - Main Courses: content/food/maincourses.md
          - Snacks: content/food/snacks.md
          - Sides, Sauces & Spice Mixes: content/food/sides.md
      - Papa's:
          - Papa's cookbook: content/food/papacookbook.md
          
  - Links:
      - content/links/index.md
      - Essays & Articles: content/links/essays.md
      - Procrastination: content/links/procrastination.md
      - Site Discovery: content/links/sites.md
      - Interesting: content/links/interesting.md
      - Podcasts: content/links/podcasts.md
      - Privacy: content/links/privacy.md
      - Piracy: content/links/piracy.md
      - IT: content/links/it.md
  - Extras:
      - content/extras/index.md
      - Best Of: content/extras/bestof.md
      - Recommendations: content/extras/recs.md

site_name: JamFox's Documentation
site_author: JamFox
site_url: https://docs.jamfox.dev/
edit_uri: docs.jamfox.dev/edit/master/docs/
docs_dir: docs
repo_name: github.com/JamFox
repo_url: https://github.com/JamFox/

theme:
  name: material
  language: en
  # custom_dir: overrides
  favicon: assets/icon.png
  logo: assets/icon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - header.autohide
    #- navigation.expand
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tabs.sticky
    - content.tabs.link
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.action.view
    - navigation.indexes
    - navigation.prune 
    #- toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: "Noto Sans"
    code: "Roboto Mono"

plugins:
  - search
  - glightbox
  # - pdf-export
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

markdown_extensions:
  - def_list
  - admonition
  - meta
  - md_in_html
  - attr_list
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      linenums_style: table
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      title: On this page
      permalink: ඞ
      permalink_title: Anchor link to this section for reference

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/solid/house
      link: https://jamfox.dev/
    - icon: fontawesome/brands/github
      link: https://github.com/JamFox
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/katurv/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/karlturvas/
#    - icon: fontawesome/brands/steam
#      link: https://steamcommunity.com/id/JamFox/
#    - icon: fontawesome/brands/spotify
#      link: https://open.spotify.com/user/kapikmeow
