name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/setup-node@v4
        with:
          node-version: 19
      - name: Install Playwright Browsers
        run: npx playwright@1.41.2 install --with-deps
      - run: pip install mkdocs-material mkdocs-minify-plugin mkdocs-glightbox mkdocs-exporter
      - run: mkdocs gh-deploy --force
